/*! Copyright (C) Microsoft Corporation. All rights reserved. */
var WebPageViewerHelper={Initialize:function(){var i,n,t;if(WebPageViewerHelper.IsRunningOnIos())return;i=Microsoft.Dynamics.NAV.GetImageResource("Loader.gif"),n=document.createElement("div"),n.setAttribute("id","spinner"),t=document.createElement("img"),t.setAttribute("src",i),n.appendChild(t),document.body.insertBefore(n,document.body.childNodes[0])},DisplaySpinner:function(){var n=document.getElementById("spinner"),t;n!=null&&n.setAttribute("style","display: block"),t=document.getElementById("controlAddIn"),t.display="none"},HideSpinner:function(){var n=document.getElementById("spinner"),t;n!=null&&n.setAttribute("style","display: none"),t=document.getElementById("controlAddIn"),t.display="block"},CreateIFrame:function(n,t){WebPageViewerHelper.DisplaySpinner();var i=document.createElement("iframe");return i.setAttribute("height",n),i.setAttribute("width",t),i.setAttribute("frameBorder","0"),i.setAttribute("seamless","seamless"),i},IFrameReady:function(n,t){var i=function(){WebPageViewerHelper.HideSpinner(),n.removeEventListener("load",i)},r=setInterval(function(){try{if(n.contentDocument&&n.contentDocument.body){n.addEventListener("load",i),n.contentDocument.body.setAttribute("style","margin: 0px; padding: 0px;");var u={preventLoadEvent:function(){n.removeEventListener("load",i)}};t(u),clearInterval(r)}}catch(f){clearInterval(r)}},5)},CreateInput:function(n,t){var i=document.createElement("input");return i.setAttribute("type","hidden"),i.setAttribute("name",n),i.setAttribute("value",t),i},CreateFormWithData:function(n,t,i){var r,u,f;if(!(n.toUpperCase()==="GET"||n.toUpperCase()==="POST"))throw"Unsupported Method Specified";if(t.substring(0,8).toLowerCase()!=="https://")throw"Insecure URL Specified";r=document.createElement("form"),r.setAttribute("method",n),r.setAttribute("action",t);for(u in i)f=WebPageViewerHelper.CreateInput(decodeURIComponent(u),decodeURIComponent(i[u])),r.appendChild(f);return r},RunJavascript:function(n,t){var i=document.createElement("script");i.type="text/javascript",i.text=n,t.head.appendChild(i)},SetBodyContent:function(n){var t=window.document.getElementById("controlAddIn");t.innerHTML="",t.appendChild(n),WebPageViewerHelper.IsRunningOnIos()&&t.classList.add("ms-dyn-nav-scrollable"),WebPageViewerHelper.Properties.BodyContent=n},GetCallbackURL:function(){var i=document.location.protocol,t=document.location.host,n=Microsoft.Dynamics.NAV.GetImageResource("callback.html");return t==""?n:n.indexOf(i+"//")==0?n:i+"//"+t+n},TriggerCallback:function(n){Microsoft.Dynamics.NAV.InvokeExtensibilityMethod("Callback",[n])},ChildDocumentReady:function(){Microsoft.Dynamics.NAV.InvokeExtensibilityMethod("DocumentReady")},TriggerEvent:function(n){var i=WebPageViewerHelper.Properties.BodyContent,t;if(!(i&&i.contentWindow))return;i.contentDocument.createEvent?(t=i.contentDocument.createEvent("CustomEvent"),t.initEvent("webpageviewerevent",!0,!0),t.data=n):t=new CustomEvent("webpageviewerevent",n),window.dispatchEvent(t)},LinksOpenInNewWindow:function(){var i=WebPageViewerHelper.Properties.BodyContent,t,n;if(!i||!i.contentDocument)return;for(i=i.contentDocument,t=i.getElementsByTagName("a"),n=0;n<t.length;n++)t[n].hasAttribute("href")&&function(){var i=t[n].getAttribute("href");t[n].setAttribute("href","#"),t[n].addEventListener("click",function(n){Microsoft.Dynamics.NAV.OpenWindow(i),n.preventDefault()})}()},UpdateLinks:function(){WebPageViewerHelper.Properties.LinksOpenInNewWindow&&WebPageViewerHelper.LinksOpenInNewWindow()},SetCallbacksFromSubscribedEventToIgnore:function(n,t){WebPageViewerHelper.Properties.IgnoreCallbacks[n]=t},SubscribeToEvent:function(n,t){WebPageViewerHelper.Properties.SubscribedEvents.indexOf(n)<0&&(WebPageViewerHelper.Properties.SubscribedEvents.push(n),window.addEventListener(n,t))},HandleException:function(n){var u=n+".",f="Please contact your system administrator.",t=document.createElement("div"),i=document.createElement("h1"),r=document.createElement("h2");t.textContent===""?(i.textContent=u,r.textContent=f):(i.innerText=u,r.innerText=f),t.appendChild(i),t.appendChild(r),WebPageViewerHelper.SetBodyContent(t)},IsRunningOnIos:function(){return WebPageViewerHelper.FindInUserAgentString("IPAD")||WebPageViewerHelper.FindInUserAgentString("IPOD")||WebPageViewerHelper.FindInUserAgentString("IPHONE")},FindInUserAgentString:function(n){return WebPageViewerHelper.GetUserAgentString().indexOf(n)>-1},GetUserAgentString:function(){return WebPageViewerHelper.Properties.UserAgentString==null&&(WebPageViewerHelper.Properties.UserAgentString=window.navigator.userAgent.toUpperCase()),WebPageViewerHelper.Properties.UserAgentString},BindSrcLoadEvent:function(n){var i=!1,t=[],r=function(){if(n.src){n.removeEventListener("load",r),i=!0;for(var u=0;u<t.length;u++)t[u]()}};return n.addEventListener("load",r),function(n){typeof n=="function"&&t.indexOf(n)<0&&(t.push(n),i&&n())}},Properties:{BodyContent:null,LinksOpenInNewWindow:!1,UserAgentString:null,SubscribedEvents:[],IgnoreCallbacks:{}}};
// SIG // Begin signature block
// SIG // MIIj7gYJKoZIhvcNAQcCoIIj3zCCI9sCAQExDzANBglg
// SIG // hkgBZQMEAgEFADB3BgorBgEEAYI3AgEEoGkwZzAyBgor
// SIG // BgEEAYI3AgEeMCQCAQEEEBDgyQbOONQRoqMAEEvTUJAC
// SIG // AQACAQACAQACAQACAQAwMTANBglghkgBZQMEAgEFAAQg
// SIG // GFkGk6PSTmBLdtPHAapOGMCjwBLoDPvUN9926r7EHryg
// SIG // gg2BMIIF/zCCA+egAwIBAgITMwAAAd9r8C6Sp0q00AAA
// SIG // AAAB3zANBgkqhkiG9w0BAQsFADB+MQswCQYDVQQGEwJV
// SIG // UzETMBEGA1UECBMKV2FzaGluZ3RvbjEQMA4GA1UEBxMH
// SIG // UmVkbW9uZDEeMBwGA1UEChMVTWljcm9zb2Z0IENvcnBv
// SIG // cmF0aW9uMSgwJgYDVQQDEx9NaWNyb3NvZnQgQ29kZSBT
// SIG // aWduaW5nIFBDQSAyMDExMB4XDTIwMTIxNTIxMzE0NVoX
// SIG // DTIxMTIwMjIxMzE0NVowdDELMAkGA1UEBhMCVVMxEzAR
// SIG // BgNVBAgTCldhc2hpbmd0b24xEDAOBgNVBAcTB1JlZG1v
// SIG // bmQxHjAcBgNVBAoTFU1pY3Jvc29mdCBDb3Jwb3JhdGlv
// SIG // bjEeMBwGA1UEAxMVTWljcm9zb2Z0IENvcnBvcmF0aW9u
// SIG // MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEA
// SIG // trsZWRAAo6nx5LhcqAsHy9uaHyPQ2VireMBI9yQUOPBj
// SIG // 7dVLA7/N+AnKFFDzJ7P+grT6GkOE4cv5GzjoP8yQJ6yX
// SIG // ojEKkXti7HW/zUiNoF11/ZWndf8j1Azl6OBjcD416tSW
// SIG // Yvh2VfdW1K+mY83j49YPm3qbKnfxwtV0nI9H092gMS0c
// SIG // pCUsxMRAZlPXksrjsFLqvgq4rnULVhjHSVOudL/yps3z
// SIG // OOmOpaPzAp56b898xC+zzHVHcKo/52IRht1FSC8V+7QH
// SIG // TG8+yzfuljiKU9QONa8GqDlZ7/vFGveB8IY2ZrtUu98n
// SIG // le0WWTcaIRHoCYvWGLLF2u1GVFJAggPipwIDAQABo4IB
// SIG // fjCCAXowHwYDVR0lBBgwFgYKKwYBBAGCN0wIAQYIKwYB
// SIG // BQUHAwMwHQYDVR0OBBYEFDj2zC/CHZDRrQnzJlT7byOl
// SIG // WfPjMFAGA1UdEQRJMEekRTBDMSkwJwYDVQQLEyBNaWNy
// SIG // b3NvZnQgT3BlcmF0aW9ucyBQdWVydG8gUmljbzEWMBQG
// SIG // A1UEBRMNMjMwMDEyKzQ2MzAwOTAfBgNVHSMEGDAWgBRI
// SIG // bmTlUAXTgqoXNzcitW2oynUClTBUBgNVHR8ETTBLMEmg
// SIG // R6BFhkNodHRwOi8vd3d3Lm1pY3Jvc29mdC5jb20vcGtp
// SIG // b3BzL2NybC9NaWNDb2RTaWdQQ0EyMDExXzIwMTEtMDct
// SIG // MDguY3JsMGEGCCsGAQUFBwEBBFUwUzBRBggrBgEFBQcw
// SIG // AoZFaHR0cDovL3d3dy5taWNyb3NvZnQuY29tL3BraW9w
// SIG // cy9jZXJ0cy9NaWNDb2RTaWdQQ0EyMDExXzIwMTEtMDct
// SIG // MDguY3J0MAwGA1UdEwEB/wQCMAAwDQYJKoZIhvcNAQEL
// SIG // BQADggIBAJ56h7Q8mFBWlQJLwCtHqqup4aC/eUmULt0Z
// SIG // 6We7XUPPUEd/vuwPuIa6+1eMcZpAeQTm0tGCvjACxNNm
// SIG // rY8FoD3aWEOvFnSxq6CWR5G2XYBERvu7RExZd2iheCqa
// SIG // EmhjrJGV6Uz5wmjKNj16ADFTBqbEBELMIpmatyEN50UH
// SIG // wZSdD6DDHDf/j5LPGUy9QaD2LCaaJLenKpefaugsqWWC
// SIG // MIMifPdh6bbcmxyoNWbUC1JUl3HETJboD4BHDWSWoDxI
// SIG // D2J4uG9dbJ40QIH9HckNMyPWi16k8VlFOaQiBYj09G9s
// SIG // LMc0agrchqqZBjPD/RmszvHmqJlSLQmAXCUgcgcf6UtH
// SIG // EmMAQRwGcSTg1KsUl6Ehg75k36lCV57Z1pC+KJKJNRYg
// SIG // g2eI6clzkLp2+noCF75IEO429rjtujsNJvEcJXg74TjK
// SIG // 5x7LqYjj26Myq6EmuqWhbVUofPWm1EqKEfEHWXInppqB
// SIG // YXFpBMBYOLKc72DT+JyLNfd9utVsk2kTGaHHhrp+xgk9
// SIG // kZeud7lI/hfoPeHOtwIc0quJIXS+B5RSD9nj79vbJn1J
// SIG // x7RqusmBQy509Kv2Pg4t48JaBfBFpJB0bUrl5RVG05sK
// SIG // /5Qw4G6WYioS0uwgUw499iNC+Yud9vrh3M8PNqGQ5mJm
// SIG // JiFEjG2ToEuuYe/e64+SSejpHhFCaAFcMIIHejCCBWKg
// SIG // AwIBAgIKYQ6Q0gAAAAAAAzANBgkqhkiG9w0BAQsFADCB
// SIG // iDELMAkGA1UEBhMCVVMxEzARBgNVBAgTCldhc2hpbmd0
// SIG // b24xEDAOBgNVBAcTB1JlZG1vbmQxHjAcBgNVBAoTFU1p
// SIG // Y3Jvc29mdCBDb3Jwb3JhdGlvbjEyMDAGA1UEAxMpTWlj
// SIG // cm9zb2Z0IFJvb3QgQ2VydGlmaWNhdGUgQXV0aG9yaXR5
// SIG // IDIwMTEwHhcNMTEwNzA4MjA1OTA5WhcNMjYwNzA4MjEw
// SIG // OTA5WjB+MQswCQYDVQQGEwJVUzETMBEGA1UECBMKV2Fz
// SIG // aGluZ3RvbjEQMA4GA1UEBxMHUmVkbW9uZDEeMBwGA1UE
// SIG // ChMVTWljcm9zb2Z0IENvcnBvcmF0aW9uMSgwJgYDVQQD
// SIG // Ex9NaWNyb3NvZnQgQ29kZSBTaWduaW5nIFBDQSAyMDEx
// SIG // MIICIjANBgkqhkiG9w0BAQEFAAOCAg8AMIICCgKCAgEA
// SIG // q/D6chAcLq3YbqqCEE00uvK2WCGfQhsqa+laUKq4Bjga
// SIG // BEm6f8MMHt03a8YS2AvwOMKZBrDIOdUBFDFC04kNeWSH
// SIG // fpRgJGyvnkmc6Whe0t+bU7IKLMOv2akrrnoJr9eWWcpg
// SIG // GgXpZnboMlImEi/nqwhQz7NEt13YxC4Ddato88tt8zpc
// SIG // oRb0RrrgOGSsbmQ1eKagYw8t00CT+OPeBw3VXHmlSSnn
// SIG // Db6gE3e+lD3v++MrWhAfTVYoonpy4BI6t0le2O3tQ5GD
// SIG // 2Xuye4Yb2T6xjF3oiU+EGvKhL1nkkDstrjNYxbc+/jLT
// SIG // swM9sbKvkjh+0p2ALPVOVpEhNSXDOW5kf1O6nA+tGSOE
// SIG // y/S6A4aN91/w0FK/jJSHvMAhdCVfGCi2zCcoOCWYOUo2
// SIG // z3yxkq4cI6epZuxhH2rhKEmdX4jiJV3TIUs+UsS1Vz8k
// SIG // A/DRelsv1SPjcF0PUUZ3s/gA4bysAoJf28AVs70b1FVL
// SIG // 5zmhD+kjSbwYuER8ReTBw3J64HLnJN+/RpnF78IcV9uD
// SIG // jexNSTCnq47f7Fufr/zdsGbiwZeBe+3W7UvnSSmnEyim
// SIG // p31ngOaKYnhfsi+E11ecXL93KCjx7W3DKI8sj0A3T8Hh
// SIG // hUSJxAlMxdSlQy90lfdu+HggWCwTXWCVmj5PM4TasIgX
// SIG // 3p5O9JawvEagbJjS4NaIjAsCAwEAAaOCAe0wggHpMBAG
// SIG // CSsGAQQBgjcVAQQDAgEAMB0GA1UdDgQWBBRIbmTlUAXT
// SIG // gqoXNzcitW2oynUClTAZBgkrBgEEAYI3FAIEDB4KAFMA
// SIG // dQBiAEMAQTALBgNVHQ8EBAMCAYYwDwYDVR0TAQH/BAUw
// SIG // AwEB/zAfBgNVHSMEGDAWgBRyLToCMZBDuRQFTuHqp8cx
// SIG // 0SOJNDBaBgNVHR8EUzBRME+gTaBLhklodHRwOi8vY3Js
// SIG // Lm1pY3Jvc29mdC5jb20vcGtpL2NybC9wcm9kdWN0cy9N
// SIG // aWNSb29DZXJBdXQyMDExXzIwMTFfMDNfMjIuY3JsMF4G
// SIG // CCsGAQUFBwEBBFIwUDBOBggrBgEFBQcwAoZCaHR0cDov
// SIG // L3d3dy5taWNyb3NvZnQuY29tL3BraS9jZXJ0cy9NaWNS
// SIG // b29DZXJBdXQyMDExXzIwMTFfMDNfMjIuY3J0MIGfBgNV
// SIG // HSAEgZcwgZQwgZEGCSsGAQQBgjcuAzCBgzA/BggrBgEF
// SIG // BQcCARYzaHR0cDovL3d3dy5taWNyb3NvZnQuY29tL3Br
// SIG // aW9wcy9kb2NzL3ByaW1hcnljcHMuaHRtMEAGCCsGAQUF
// SIG // BwICMDQeMiAdAEwAZQBnAGEAbABfAHAAbwBsAGkAYwB5
// SIG // AF8AcwB0AGEAdABlAG0AZQBuAHQALiAdMA0GCSqGSIb3
// SIG // DQEBCwUAA4ICAQBn8oalmOBUeRou09h0ZyKbC5YR4WOS
// SIG // mUKWfdJ5DJDBZV8uLD74w3LRbYP+vj/oCso7v0epo/Np
// SIG // 22O/IjWll11lhJB9i0ZQVdgMknzSGksc8zxCi1LQsP1r
// SIG // 4z4HLimb5j0bpdS1HXeUOeLpZMlEPXh6I/MTfaaQdION
// SIG // 9MsmAkYqwooQu6SpBQyb7Wj6aC6VoCo/KmtYSWMfCWlu
// SIG // WpiW5IP0wI/zRive/DvQvTXvbiWu5a8n7dDd8w6vmSiX
// SIG // mE0OPQvyCInWH8MyGOLwxS3OW560STkKxgrCxq2u5bLZ
// SIG // 2xWIUUVYODJxJxp/sfQn+N4sOiBpmLJZiWhub6e3dMNA
// SIG // BQamASooPoI/E01mC8CzTfXhj38cbxV9Rad25UAqZaPD
// SIG // XVJihsMdYzaXht/a8/jyFqGaJ+HNpZfQ7l1jQeNbB5yH
// SIG // PgZ3BtEGsXUfFL5hYbXw3MYbBL7fQccOKO7eZS/sl/ah
// SIG // XJbYANahRr1Z85elCUtIEJmAH9AAKcWxm6U/RXceNcbS
// SIG // oqKfenoi+kiVH6v7RyOA9Z74v2u3S5fi63V4GuzqN5l5
// SIG // GEv/1rMjaHXmr/r8i+sLgOppO6/8MO0ETI7f33VtY5E9
// SIG // 0Z1WTk+/gFcioXgRMiF670EKsT/7qMykXcGhiJtXcVZO
// SIG // SEXAQsmbdlsKgEhr/Xmfwb1tbWrJUnMTDXpQzTGCFcUw
// SIG // ghXBAgEBMIGVMH4xCzAJBgNVBAYTAlVTMRMwEQYDVQQI
// SIG // EwpXYXNoaW5ndG9uMRAwDgYDVQQHEwdSZWRtb25kMR4w
// SIG // HAYDVQQKExVNaWNyb3NvZnQgQ29ycG9yYXRpb24xKDAm
// SIG // BgNVBAMTH01pY3Jvc29mdCBDb2RlIFNpZ25pbmcgUENB
// SIG // IDIwMTECEzMAAAHfa/AukqdKtNAAAAAAAd8wDQYJYIZI
// SIG // AWUDBAIBBQCgggEBMBkGCSqGSIb3DQEJAzEMBgorBgEE
// SIG // AYI3AgEEMBwGCisGAQQBgjcCAQsxDjAMBgorBgEEAYI3
// SIG // AgEVMC8GCSqGSIb3DQEJBDEiBCDr2zqIw7meq0aHlZ8l
// SIG // cNk+BzVM3uLSSkBcrHfQ3qvguzCBlAYKKwYBBAGCNwIB
// SIG // DDGBhTCBgqBkgGIATQBpAGMAcgBvAHMAbwBmAHQALgBE
// SIG // AHkAbgBhAG0AaQBjAHMALgBGAHIAYQBtAGUAdwBvAHIA
// SIG // awAuAFUASQAuAFcAaQBuAEYAbwByAG0AcwAuAEMAbwBu
// SIG // AHQAcgBvAGwAc6EagBhodHRwOi8vd3d3Lm1pY3Jvc29m
// SIG // dC5jb20wDQYJKoZIhvcNAQEBBQAEggEAZi5NlNPMj/s4
// SIG // 6DHGFDkPtCTX98tryZ3ZMK4WvWiADpNtE3Mh9CqpwPHr
// SIG // u6vz40uojIXdbT9EOYsonWrxSgfypBJvx741Jfxb+5pU
// SIG // MTxgruq+ApYoTWq/w22QVxusPduHX4ZNdyzKTdvt1zKA
// SIG // ackRSMu1ipQfWOs+6TWGZ+ss2K9eNT0DfzZA/vD8esbp
// SIG // CjCg98PqpXPAMRgKga8BuK8+Oj2jDOURVq9q4LJaUO+Z
// SIG // p8DNxSkpn7zH2X12TqdFVUU7eot4omM+ywmRpL2o/B2U
// SIG // Jd0v1LdodZf8x6bblXr9KMt1OWXDdSFQxinjspru+zOm
// SIG // LImR5ACO588Tp8M7I66jiKGCEvswghL3BgorBgEEAYI3
// SIG // AwMBMYIS5zCCEuMGCSqGSIb3DQEHAqCCEtQwghLQAgED
// SIG // MQ8wDQYJYIZIAWUDBAIBBQAwggFZBgsqhkiG9w0BCRAB
// SIG // BKCCAUgEggFEMIIBQAIBAQYKKwYBBAGEWQoDATAxMA0G
// SIG // CWCGSAFlAwQCAQUABCCdYJQAbCq/HI9rAfSdP8HYkn3h
// SIG // 9EEDO6uW1OfD/YbZKQIGYUi4d3PUGBMyMDIxMDkyOTEy
// SIG // MDY1NC42NjZaMASAAgH0oIHYpIHVMIHSMQswCQYDVQQG
// SIG // EwJVUzETMBEGA1UECBMKV2FzaGluZ3RvbjEQMA4GA1UE
// SIG // BxMHUmVkbW9uZDEeMBwGA1UEChMVTWljcm9zb2Z0IENv
// SIG // cnBvcmF0aW9uMS0wKwYDVQQLEyRNaWNyb3NvZnQgSXJl
// SIG // bGFuZCBPcGVyYXRpb25zIExpbWl0ZWQxJjAkBgNVBAsT
// SIG // HVRoYWxlcyBUU1MgRVNOOjA4NDItNEJFNi1DMjlBMSUw
// SIG // IwYDVQQDExxNaWNyb3NvZnQgVGltZS1TdGFtcCBTZXJ2
// SIG // aWNloIIOSjCCBPkwggPhoAMCAQICEzMAAAE5zOjoQ4vw
// SIG // NOEAAAAAATkwDQYJKoZIhvcNAQELBQAwfDELMAkGA1UE
// SIG // BhMCVVMxEzARBgNVBAgTCldhc2hpbmd0b24xEDAOBgNV
// SIG // BAcTB1JlZG1vbmQxHjAcBgNVBAoTFU1pY3Jvc29mdCBD
// SIG // b3Jwb3JhdGlvbjEmMCQGA1UEAxMdTWljcm9zb2Z0IFRp
// SIG // bWUtU3RhbXAgUENBIDIwMTAwHhcNMjAxMDE1MTcyODIx
// SIG // WhcNMjIwMTEyMTcyODIxWjCB0jELMAkGA1UEBhMCVVMx
// SIG // EzARBgNVBAgTCldhc2hpbmd0b24xEDAOBgNVBAcTB1Jl
// SIG // ZG1vbmQxHjAcBgNVBAoTFU1pY3Jvc29mdCBDb3Jwb3Jh
// SIG // dGlvbjEtMCsGA1UECxMkTWljcm9zb2Z0IElyZWxhbmQg
// SIG // T3BlcmF0aW9ucyBMaW1pdGVkMSYwJAYDVQQLEx1UaGFs
// SIG // ZXMgVFNTIEVTTjowODQyLTRCRTYtQzI5QTElMCMGA1UE
// SIG // AxMcTWljcm9zb2Z0IFRpbWUtU3RhbXAgU2VydmljZTCC
// SIG // ASIwDQYJKoZIhvcNAQEBBQADggEPADCCAQoCggEBANoT
// SIG // +YzjJZMloY6zKgb8onj4Wh+YN09/UMHbuh6gJ1nC5c/f
// SIG // 2SqAv0Bc+OYG9GndeCL6hWhZtieqPr4YW3+KECThw03I
// SIG // 2VwSkE20E/8Oiwlr3Ql5xUJdmvJxHeNhJhO68UVZirpm
// SIG // x6BClfkMGHRnO9KuTvDNmJKif0rXKxYRbZoRcXL1WfoI
// SIG // OGs87xPO/rKCM2Fes6jNiljv00svWXqIuV+EKG1egCrs
// SIG // CR9PMkmdpUAV853fK8A88uvgWKiV4pvm/lfuxN++NW+n
// SIG // EPX5jjQKRy4ZBqqNO/wdeDZBqqjve/IQI17VaEKSoyru
// SIG // ssV87LKUJ49K5X7Ffx8klv5fos8eyk8CAwEAAaOCARsw
// SIG // ggEXMB0GA1UdDgQWBBSZnpuGclTCmdqSirGfRvZQLQYM
// SIG // 6TAfBgNVHSMEGDAWgBTVYzpcijGQ80N7fEYbxTNoWoVt
// SIG // VTBWBgNVHR8ETzBNMEugSaBHhkVodHRwOi8vY3JsLm1p
// SIG // Y3Jvc29mdC5jb20vcGtpL2NybC9wcm9kdWN0cy9NaWNU
// SIG // aW1TdGFQQ0FfMjAxMC0wNy0wMS5jcmwwWgYIKwYBBQUH
// SIG // AQEETjBMMEoGCCsGAQUFBzAChj5odHRwOi8vd3d3Lm1p
// SIG // Y3Jvc29mdC5jb20vcGtpL2NlcnRzL01pY1RpbVN0YVBD
// SIG // QV8yMDEwLTA3LTAxLmNydDAMBgNVHRMBAf8EAjAAMBMG
// SIG // A1UdJQQMMAoGCCsGAQUFBwMIMA0GCSqGSIb3DQEBCwUA
// SIG // A4IBAQBYXChq8/83GoXNwVrtQ4KIvxANsSb7uvYRiJOh
// SIG // bSDx11jIrlZrUUB3/KckPWrJz9nHH0c/3TKpcpP6vPiD
// SIG // XAixBJaUoJvdcbghWGxYQISybaKM39/Gh+a2NmcVjfW7
// SIG // gxJJyX4hoiukPvJJAjVpm1o9g8UcBBfCHwcIxexD4WA4
// SIG // HYpSs+POrsIYKLKK9Rrg1opWIxqDDat5a8AyJGP/NylK
// SIG // SYaK5aYgXZCDRLFZAn88hC5nvQt7WpmbTEl8a1GcF+lq
// SIG // 393UmBAKst+jyWSa4sE8Ib84yHqg/His1FId7nxNvxIx
// SIG // AG2mwYQqNvrVKMp0+kwCbY3Yr2uIOz+9/1UK0nDHMIIG
// SIG // cTCCBFmgAwIBAgIKYQmBKgAAAAAAAjANBgkqhkiG9w0B
// SIG // AQsFADCBiDELMAkGA1UEBhMCVVMxEzARBgNVBAgTCldh
// SIG // c2hpbmd0b24xEDAOBgNVBAcTB1JlZG1vbmQxHjAcBgNV
// SIG // BAoTFU1pY3Jvc29mdCBDb3Jwb3JhdGlvbjEyMDAGA1UE
// SIG // AxMpTWljcm9zb2Z0IFJvb3QgQ2VydGlmaWNhdGUgQXV0
// SIG // aG9yaXR5IDIwMTAwHhcNMTAwNzAxMjEzNjU1WhcNMjUw
// SIG // NzAxMjE0NjU1WjB8MQswCQYDVQQGEwJVUzETMBEGA1UE
// SIG // CBMKV2FzaGluZ3RvbjEQMA4GA1UEBxMHUmVkbW9uZDEe
// SIG // MBwGA1UEChMVTWljcm9zb2Z0IENvcnBvcmF0aW9uMSYw
// SIG // JAYDVQQDEx1NaWNyb3NvZnQgVGltZS1TdGFtcCBQQ0Eg
// SIG // MjAxMDCCASIwDQYJKoZIhvcNAQEBBQADggEPADCCAQoC
// SIG // ggEBAKkdDbx3EYo6IOz8E5f1+n9plGt0VBDVpQoAgoX7
// SIG // 7XxoSyxfxcPlYcJ2tz5mK1vwFVMnBDEfQRsalR3OCROO
// SIG // fGEwWbEwRA/xYIiEVEMM1024OAizQt2TrNZzMFcmgqNF
// SIG // DdDq9UeBzb8kYDJYYEbyWEeGMoQedGFnkV+BVLHPk0yS
// SIG // wcSmXdFhE24oxhr5hoC732H8RsEnHSRnEnIaIYqvS2SJ
// SIG // UGKxXf13Hz3wV3WsvYpCTUBR0Q+cBj5nf/VmwAOWRH7v
// SIG // 0Ev9buWayrGo8noqCjHw2k4GkbaICDXoeByw6ZnNPOcv
// SIG // RLqn9NxkvaQBwSAJk3jN/LzAyURdXhacAQVPIk0CAwEA
// SIG // AaOCAeYwggHiMBAGCSsGAQQBgjcVAQQDAgEAMB0GA1Ud
// SIG // DgQWBBTVYzpcijGQ80N7fEYbxTNoWoVtVTAZBgkrBgEE
// SIG // AYI3FAIEDB4KAFMAdQBiAEMAQTALBgNVHQ8EBAMCAYYw
// SIG // DwYDVR0TAQH/BAUwAwEB/zAfBgNVHSMEGDAWgBTV9lbL
// SIG // j+iiXGJo0T2UkFvXzpoYxDBWBgNVHR8ETzBNMEugSaBH
// SIG // hkVodHRwOi8vY3JsLm1pY3Jvc29mdC5jb20vcGtpL2Ny
// SIG // bC9wcm9kdWN0cy9NaWNSb29DZXJBdXRfMjAxMC0wNi0y
// SIG // My5jcmwwWgYIKwYBBQUHAQEETjBMMEoGCCsGAQUFBzAC
// SIG // hj5odHRwOi8vd3d3Lm1pY3Jvc29mdC5jb20vcGtpL2Nl
// SIG // cnRzL01pY1Jvb0NlckF1dF8yMDEwLTA2LTIzLmNydDCB
// SIG // oAYDVR0gAQH/BIGVMIGSMIGPBgkrBgEEAYI3LgMwgYEw
// SIG // PQYIKwYBBQUHAgEWMWh0dHA6Ly93d3cubWljcm9zb2Z0
// SIG // LmNvbS9QS0kvZG9jcy9DUFMvZGVmYXVsdC5odG0wQAYI
// SIG // KwYBBQUHAgIwNB4yIB0ATABlAGcAYQBsAF8AUABvAGwA
// SIG // aQBjAHkAXwBTAHQAYQB0AGUAbQBlAG4AdAAuIB0wDQYJ
// SIG // KoZIhvcNAQELBQADggIBAAfmiFEN4sbgmD+BcQM9naOh
// SIG // IW+z66bM9TG+zwXiqf76V20ZMLPCxWbJat/15/B4vceo
// SIG // niXj+bzta1RXCCtRgkQS+7lTjMz0YBKKdsxAQEGb3FwX
// SIG // /1z5Xhc1mCRWS3TvQhDIr79/xn/yN31aPxzymXlKkVIA
// SIG // rzgPF/UveYFl2am1a+THzvbKegBvSzBEJCI8z+0DpZaP
// SIG // WSm8tv0E4XCfMkon/VWvL/625Y4zu2JfmttXQOnxzplm
// SIG // kIz/amJ/3cVKC5Em4jnsGUpxY517IW3DnKOiPPp/fZZq
// SIG // kHimbdLhnPkd/DjYlPTGpQqWhqS9nhquBEKDuLWAmyI4
// SIG // ILUl5WTs9/S/fmNZJQ96LjlXdqJxqgaKD4kWumGnEcua
// SIG // 2A5HmoDF0M2n0O99g/DhO3EJ3110mCIIYdqwUB5vvfHh
// SIG // AN/nMQekkzr3ZUd46PioSKv33nJ+YWtvd6mBy6cJrDm7
// SIG // 7MbL2IK0cs0d9LiFAR6A+xuJKlQ5slvayA1VmXqHczsI
// SIG // 5pgt6o3gMy4SKfXAL1QnIffIrE7aKLixqduWsqdCosnP
// SIG // GUFN4Ib5KpqjEWYw07t0MkvfY3v1mYovG8chr1m1rtxE
// SIG // PJdQcdeh0sVV42neV8HR3jDA/czmTfsNv11P6Z0eGTgv
// SIG // vM9YBS7vDaBQNdrvCScc1bN+NR4Iuto229Nfj950iEkS
// SIG // oYIC1DCCAj0CAQEwggEAoYHYpIHVMIHSMQswCQYDVQQG
// SIG // EwJVUzETMBEGA1UECBMKV2FzaGluZ3RvbjEQMA4GA1UE
// SIG // BxMHUmVkbW9uZDEeMBwGA1UEChMVTWljcm9zb2Z0IENv
// SIG // cnBvcmF0aW9uMS0wKwYDVQQLEyRNaWNyb3NvZnQgSXJl
// SIG // bGFuZCBPcGVyYXRpb25zIExpbWl0ZWQxJjAkBgNVBAsT
// SIG // HVRoYWxlcyBUU1MgRVNOOjA4NDItNEJFNi1DMjlBMSUw
// SIG // IwYDVQQDExxNaWNyb3NvZnQgVGltZS1TdGFtcCBTZXJ2
// SIG // aWNloiMKAQEwBwYFKw4DAhoDFQANTZT+G96WhI10Px3u
// SIG // SgTGs2WMB6CBgzCBgKR+MHwxCzAJBgNVBAYTAlVTMRMw
// SIG // EQYDVQQIEwpXYXNoaW5ndG9uMRAwDgYDVQQHEwdSZWRt
// SIG // b25kMR4wHAYDVQQKExVNaWNyb3NvZnQgQ29ycG9yYXRp
// SIG // b24xJjAkBgNVBAMTHU1pY3Jvc29mdCBUaW1lLVN0YW1w
// SIG // IFBDQSAyMDEwMA0GCSqGSIb3DQEBBQUAAgUA5P5rVzAi
// SIG // GA8yMDIxMDkyOTEyMzQzMVoYDzIwMjEwOTMwMTIzNDMx
// SIG // WjB0MDoGCisGAQQBhFkKBAExLDAqMAoCBQDk/mtXAgEA
// SIG // MAcCAQACAiCxMAcCAQACAhOPMAoCBQDk/7zXAgEAMDYG
// SIG // CisGAQQBhFkKBAIxKDAmMAwGCisGAQQBhFkKAwKgCjAI
// SIG // AgEAAgMHoSChCjAIAgEAAgMBhqAwDQYJKoZIhvcNAQEF
// SIG // BQADgYEAqQatWIAWID7ARF+9Jid6dGEx3GuAPUtIWldE
// SIG // Z8CJPuL9F23Xz2j+riAiXF1NM2cuiqVg3X25Y5mlQ5od
// SIG // 2FrLP/PGcQh0x4wUulKHKepIzdOKIp7BZy2FT+mKUyYF
// SIG // rizIeWJyFbIFIM47jDDC2Arroyp9DNahuXNA+K7t8fiB
// SIG // 6RYxggMNMIIDCQIBATCBkzB8MQswCQYDVQQGEwJVUzET
// SIG // MBEGA1UECBMKV2FzaGluZ3RvbjEQMA4GA1UEBxMHUmVk
// SIG // bW9uZDEeMBwGA1UEChMVTWljcm9zb2Z0IENvcnBvcmF0
// SIG // aW9uMSYwJAYDVQQDEx1NaWNyb3NvZnQgVGltZS1TdGFt
// SIG // cCBQQ0EgMjAxMAITMwAAATnM6OhDi/A04QAAAAABOTAN
// SIG // BglghkgBZQMEAgEFAKCCAUowGgYJKoZIhvcNAQkDMQ0G
// SIG // CyqGSIb3DQEJEAEEMC8GCSqGSIb3DQEJBDEiBCBIqoMd
// SIG // favyuKcCJC7Bne/HKm35Pj+mPlsu3iZ6BMvwVTCB+gYL
// SIG // KoZIhvcNAQkQAi8xgeowgecwgeQwgb0EIDyhjuQ4o9ck
// SIG // ezFCseKBBa58alUn85p6nyam1KAHD/yfMIGYMIGApH4w
// SIG // fDELMAkGA1UEBhMCVVMxEzARBgNVBAgTCldhc2hpbmd0
// SIG // b24xEDAOBgNVBAcTB1JlZG1vbmQxHjAcBgNVBAoTFU1p
// SIG // Y3Jvc29mdCBDb3Jwb3JhdGlvbjEmMCQGA1UEAxMdTWlj
// SIG // cm9zb2Z0IFRpbWUtU3RhbXAgUENBIDIwMTACEzMAAAE5
// SIG // zOjoQ4vwNOEAAAAAATkwIgQgftD3yXjlVuQQYoj0liww
// SIG // 4aE38wbU2uIQSi4nC83GT48wDQYJKoZIhvcNAQELBQAE
// SIG // ggEAVceKo1zblIwNsbYoYKWTDKTaFYEVZp811mSDyBV6
// SIG // ebI4X1r9YYG3wNZX7aq+I7DBf2F4E3GII9CJqIR9g07S
// SIG // gRpFHlV4275d9J2+1NNcDULBD/4DVlUcnXroNlZ1WD7Z
// SIG // +pIYOqZBXADkBYUc9eniWnFixycWtG8IKkMduqsz1X+3
// SIG // V4SNnYNXySzI/cT3iiC/qpoCKHL992mcdLKA0HLF9H6Y
// SIG // eDbfHizwnxaydbkTeK7LQmcQG/BRlg+p0/Ft8QNnSopG
// SIG // aXkpFAljBt6p8L4wvz7tsPXXNXj2uFwWtfXLNjcOPX2D
// SIG // 0MBNNwgMrR/tBvJQJUgSq/Ibiiy4JYceM3DvFQ==
// SIG // End signature block
