/*! Copyright (C) Microsoft Corporation. All rights reserved. */
function Initialize(){$(window).resize(function(){var n=$(this).width(),t=$(this).height();onChartSizeChanged(n,t)}),raiseAddInReady()}function Update(n){chart==null||chart.tooltip==null||chart.tooltip.isHidden?createUI(n):(chart.tooltip.hide(),createUIWhenToolTipIsHidden(n))}function Refresh(){raiseRefresh()}function raiseAddInReady(){Microsoft.Dynamics.NAV.InvokeExtensibilityMethod("AddInReady",null)}function raiseRefresh(){Microsoft.Dynamics.NAV.InvokeExtensibilityMethod("Refresh",null)}function raiseDataPointClicked(n){Microsoft.Dynamics.NAV.InvokeExtensibilityMethod("DataPointClicked",[n],!0)}function createUIWhenToolTipIsHidden(n){chart.tooltip.isHidden?createUI(n):window.setTimeout(function(){createUIWhenToolTipIsHidden(n),n=null},100)}function createUI(n){chart!=null&&(chart.destroy(),chart=null),$("#controlAddIn").empty(),validateChartData(n)&&(initializeChartLanguage(n),createChart(n))}function validateChartData(n){return validateData(n)?validateYAxisRange(n)?!0:!1:!1}function validateData(n){return n.XDimensionColumn==null||n.XDimensionColumn.ColumnName==null||n.Measures==null||n.Measures.length==0||n.DataTable==null||n.DataTable.length==0||chartDataContainsEmptyPie(n)?(createMessage(n.Resources.NoDataAvailable),!1):!0}function validateYAxisRange(n){return!isNaN(n.YAxisMinimum)&&!isNaN(n.YAxisMaximum)&&n.YAxisMinimum>=n.YAxisMaximum?(createMessage(n.Resources.YAxisRangeInvalid),!1):!0}function createMessage(n){$("#controlAddIn").append('<div class="'+getMessageClassName()+'"><span>'+n+"</span></div>")}function initializeChartLanguage(n){Highcharts.setOptions({lang:{months:n.Resources.MonthNames,shortMonths:n.Resources.ShortMonthNames,weekdays:n.Resources.WeekdayNames,accessibility:n.Resources.Accessibility}})}function createPalette(){return useModena365Theme()?["rgba(80, 93, 109, 0.8)","rgba(167, 173, 182, 0.8)","rgba(0, 128, 137, 0.8)","rgba(0, 183, 195, 0.8)","rgba(166, 230, 234, 0.8)","rgba(201, 196, 114, 0.8)","rgba(136, 206, 129, 0.8)","rgba(233, 119, 104, 0.8)","rgba(117, 181, 231, 0.8)","rgba(133, 141, 153, 0.8)","rgba(229, 231, 233, 0.8)","rgba(89, 204, 180, 0.8)","rgba(117, 216, 231, 0.8)","rgba(238, 234, 134, 0.8)","rgba(232, 158, 99, 0.8)","rgba(219, 189, 235, 0.8)","rgba(203, 206, 211, 0.8)","rgba(57, 178, 148, 0.8)","rgba(115, 186, 90, 0.8)","rgba(230, 94, 109, 0.8)"]:["rgba(15, 111, 198, 0.8)","rgba(195, 38, 12, 0.8)","rgba(84, 158, 57, 0.8)","rgba(155, 87, 211, 0.8)","rgba(62, 204, 180, 0.8)","rgba(255, 185, 29, 0.8)","rgba(180, 21, 109, 0.8)","rgba(255, 132, 39, 0.8)","rgba(177, 204, 41, 0.8)","rgba(41, 204, 82, 0.8)","rgba(36, 36, 102, 0.8)","rgba(229, 115, 229, 0.8)"]}function getToolTipEnabled(){return!0}function getTooltipHeaderCaption(n){var t=n.XDimensionColumn.Caption;return t==null&&(t=n.XDimensionColumn.ColumnName),t}function getToolTipHeaderFormat(n){var t=getTooltipHeaderCaption(n);return'<span class="addInToolTipHeader">'+t+": {point.key}</span><table>"}function getToolTipPointFormat(){return'<tr><td class="addInToolTipPointName"><span style="color:{series.color}">●</span> {series.name}: </td><td class="addInToolTipPointValue">{point.y}</td></tr>'}function getToolTipFooterFormat(){return"</table>"}function createChart(n){var i,r;stackIndex=0;var t=getXAxisType(n),u=!0,f=getVerticalAlignmentLegend(n);chart=new Highcharts.Chart({accessibility:{point:{descriptionFormatter:function(t){var i=getTooltipHeaderCaption(n),r=t.series.type==="pie"?Math.round(t.percentage)+"%":t.y;return i+": "+t.name+", "+t.series.name+": "+r}},keyboardNavigation:{order:getKeyboardOrder(u,f)},screenReaderSection:{beforeChartFormat:BEFORE_CHART_FORMAT_TEMPLATE}},chart:{renderTo:"controlAddIn",type:getDefaultSerieType(n),polar:getPolarSeriesType(n)},colors:createPalette(),credits:{enabled:!1},exporting:{enabled:!1},legend:{align:getHorizontalAlignmentLegend(n),borderWidth:0,enabled:u,itemStyle:{fontWeight:"normal"},margin:20,navigation:{style:{fontWeight:"normal"}},verticalAlign:f},plotOptions:{area:{stacking:getAreaSeriesStacking(n),trackByArea:!0},column:{borderWidth:1,groupPadding:.1,pointPadding:0,stacking:getColumnSeriesStacking(n)},funnel:{dataLabels:{connectorWidth:0,distance:10}},pie:{dataLabels:{connectorWidth:0,distance:10,enabled:!1},showInLegend:!0},series:{animation:!0,cursor:"pointer",point:{events:{click:onPointClick,mouseOver:function(){var n=!1;this.update({color:this.color},n)}}},stickyTracking:!1}},series:getSeries(n,t),title:{text:null},tooltip:{enabled:getToolTipEnabled(),footerFormat:getToolTipFooterFormat(),headerFormat:getToolTipHeaderFormat(n),hideDelay:0,pointFormat:getToolTipPointFormat(),backgroundColor:"rgba(247, 247, 247, .9)",borderWidth:0,shared:!0,useHTML:!0},xAxis:{minTickInterval:getXAxisMinTickInterval(t),type:t},yAxis:{min:getYAxisMin(n),max:getYAxisMax(n),reversedStacks:!1,title:{text:null}}},function(n){for(var r=n.renderer.box,i=r.getElementsByTagName("desc"),t=i.length-1;t>=0;t--)i[t].innerHTML=""}),$(chart.container).find("svg").attr("focusable","false"),i=$(chart.container).width(),r=$(chart.container).height(),i>0&&r>0&&onSizeChanged(i,r)}function getSeries(n,t){for(var e=[],i,u,f,r=0;r<n.Measures.length;r++)i=n.Measures[r],u=getSerieStacking(n,i),f=u!=null?u:stackIndex++,e[r]={data:getSerieData(n,i,t),innerSize:getSerieInnerSize(n,i),lineWidth:getSerieLineWidth(n,i),marker:getSerieMarker(n,i),name:i,stack:f,step:getSerieLineStep(n,i),type:getSerieType(n,i)};return e}function getSerieData(n,t,i){for(var u=[],f,r=0;r<n.DataTable.length;r++)f=n.DataTable[r][n.XDimensionColumn.ColumnName],u[r]=i=="datetime"?{x:Date.parse(f),y:n.DataTable[r][t]}:{name:f,y:n.DataTable[r][t]};return u}function getDefaultSerieType(n){return getChartType(n.DefaultType)}function getSerieType(n,t){return getChartType(n.MeasureTypes[t])}function getChartType(n){switch(n){case 0:case 3:case 5:return"line";case 10:case 11:case 12:return"column";case 13:case 15:case 16:return"area";case 17:case 18:return"pie";case 25:return"area";case 33:return"funnel"}throw"unsupported chart type";}function getColumnSeriesStacking(n){for(var i,r,t=0;t<n.Measures.length;t++){i=n.Measures[t],r=n.MeasureTypes[i];switch(r){case 11:case 12:return getSerieStacking(n,n.Measures[t])}}return null}function getAreaSeriesStacking(n){for(var i,r,t=0;t<n.Measures.length;t++){i=n.Measures[t],r=n.MeasureTypes[i];switch(r){case 15:case 16:return getSerieStacking(n,n.Measures[t])}}return null}function getSerieStacking(n,t){var i=n.MeasureTypes[t];switch(i){case 11:case 15:return"normal";case 12:case 16:return"percent"}return null}function getSerieLineWidth(n,t){var i=n.MeasureTypes[t];switch(i){case 0:case 13:case 15:case 16:return 0}return 2}function getSerieLineStep(n,t){var i=n.MeasureTypes[t];switch(i){case 5:return"left"}return!1}function getHideSerieMarker(n,t){var i=n.MeasureTypes[t];switch(i){case 0:return!1;default:return!0}}function getSerieMarker(n,t){var i=getHideSerieMarker(n,t);return{enabled:!0,states:{hover:{enabled:!0,radius:HOVER_MARKER_RADIUS}},radius:i?HIDDEN_MARKER_RADIUS:DEFAULT_MARKER_RADIUS}}function getSerieInnerSize(n,t){var i=n.MeasureTypes[t];switch(i){case 18:return useModena365Theme()?"65%":"40%"}return 0}function getPolarSeriesType(n){for(var i,t=0;t<n.Measures.length;t++){i=getPolarSerieType(n,n.Measures[t]);if(i)return i}return!1}function getPolarSerieType(n,t){var i=n.MeasureTypes[t];switch(i){case 25:return!0}return!1}function getXAxisType(n){return n.XDimensionColumn.DataType.indexOf("System.DateTime")==0?"datetime":"category"}function getXAxisMinTickInterval(n){return n=="datetime"?864e5:null}function getYAxisMin(n){return isNaN(n.YAxisMinimum)?null:n.YAxisMinimum}function getYAxisMax(n){return isNaN(n.YAxisMaximum)?null:n.YAxisMaximum}function getXAxisLabelsMaxStaggerLines(n){return n<260?1:n<320?2:n<380?3:4}function getXAxisLabelsStep(n,t,i){var e=0,r,u,f;if(t<=0)return e;for(r=0,u=0;u<i.length;u++){f=i[u];if(f==null)continue;f.length>r&&(r=f.length)}var h=r*i.length,o=Math.ceil(h/n),s=o;while(t/s<8)s=o/++e;return e}function updateXAxisLabels(n,t,i){var r=getXAxisLabelsMaxStaggerLines(t),u=r>1?r:null,f=r<=1?r:null,e=getXAxisLabelsStep(r,n,chart.xAxis[0].names),o=chart.xAxis[0].names;chart.xAxis[0].update({labels:{staggerLines:f,maxStaggerLines:u,overflow:"justify",step:e}},!1),chart.xAxis[0].names=o,i&&chart.redraw()}function updateLegend(n,t,i){var r=getEnableLegend(n,t),f,u;if(chart.options.legend.enabled!=r){for(chart.options.legend.enabled=r,chart.legend.enabled=r,chart.legend.display=r,f=getKeyboardOrder(r,chart.legend.verticalAlign),chart.accessibility.keyboardNavigation.order=f,chart.options.accessibility.keyboardNavigation.order=f,u=0;u<chart.series.length;u++)chart.series[u].update({showInLegend:r},!1),chart.series[u].type=="pie"&&chart.series[u].update({dataLabels:{enabled:!r}},!1);chart.setSize()}else i&&chart.redraw();chart.options.legend.accessibility.enabled=r,chart.accessibility.components.legend.recreateProxies(),chart.accessibility.components.legend.updateLegendTitle()}function chartContainsPie(){for(var n=0;n<chart.series.length;n++)if(chart.series[n].type=="pie")return!0;return!1}function chartDataContainsPie(n){for(var t=0;t<n.Measures.length;t++)if(getSerieType(n,n.Measures[t])=="pie")return!0;return!1}function chartDataContainsEmptyPie(n){for(var e=getXAxisType(n),u,r,i,f,t=0;t<n.Measures.length;t++){u=getSerieType(n,n.Measures[t]);if(u=="pie"){for(r=getSerieData(n,n.Measures[t],e),i=0;i<r.length;i++){f=r[i].y;if(f!=0)return!1}return!0}}return!1}function getEnableLegend(n,t){return getSeriesEnableLegend(n,t)||getPieEnableLegend(n,t)}function getSeriesEnableLegend(n,t){return chart.series.length<=1?!1:t>200||!getToolTipEnabled()}function getPieEnableLegend(n,t){return chartContainsPie()?n<480||4/3*t>n:!1}function getHorizontalAlignmentLegend(n){return useModena365Theme()&&getVerticalAlignmentLegend(n)!=="bottom"?document.body.classList.add("left-align-legend"):document.body.classList.remove("left-align-legend"),"center"}function getVerticalAlignmentLegend(n){return chartDataContainsPie(n)&&Microsoft.Dynamics.NAV.GetEnvironment().DeviceCategory==2?"bottom":"top"}function getKeyboardOrder(n,t){return n?t==="top"?["legend","series"]:["series","legend"]:["series"]}function onChartSizeChanged(n,t){if(chart==null||t<=0||n<=0)return;var i=chart.xAxis[0].chart;if(i!=null&&i.chartHeight==t&&i.chartHeight==t)return;onSizeChanged(n,t)}function onSizeChanged(n,t){updateXAxisLabels(n,t,!1),updateLegend(n,t,!0)}function onPointClick(){var t,n=this;if(typeof n.name!="undefined")t=n.name;else{var i=(new Date).getTimezoneOffset(),r=(n.x/6e4-i)/1440,u=r+25569;t=Math.round(u*10)/10}raiseDataPointClicked({Measures:[n.series.name],XValueString:t,YValues:[n.y]})}function isNaN(n){return n=="NaN"}function getMessageClassName(){return"addInMessage"+getClassNameSuffix()}function getClassNameSuffix(){switch(Microsoft.Dynamics.NAV.GetEnvironment().DeviceCategory){case 0:default:return"-desktop";case 1:return"-tablet";case 2:return"-phone"}}function useModena365Theme(){return document.body.classList.contains("theme-m365")}"use strict";var chart=null,stackIndex,DEFAULT_MARKER_RADIUS=4,HOVER_MARKER_RADIUS=DEFAULT_MARKER_RADIUS+2,HIDDEN_MARKER_RADIUS=.0001,BEFORE_CHART_FORMAT_TEMPLATE="<div>{typeDescription}</div><div>{chartSubtitle}</div><div>{chartLongdesc}</div><div>{playAsSoundButton}</div><div>{viewTableButton}</div><div>{xAxisDescription}</div><div>{yAxisDescription}</div><div>{annotationsTitle}{annotationsList}</div>";
// SIG // Begin signature block
// SIG // MIIj2AYJKoZIhvcNAQcCoIIjyTCCI8UCAQExDzANBglg
// SIG // hkgBZQMEAgEFADB3BgorBgEEAYI3AgEEoGkwZzAyBgor
// SIG // BgEEAYI3AgEeMCQCAQEEEBDgyQbOONQRoqMAEEvTUJAC
// SIG // AQACAQACAQACAQACAQAwMTANBglghkgBZQMEAgEFAAQg
// SIG // bpVD3IIh1K6EfQhCUwDBdA1RGUAVJ2ECwF9UoK2wM9Og
// SIG // gg2BMIIF/zCCA+egAwIBAgITMwAAAd9r8C6Sp0q00AAA
// SIG // AAAB3zANBgkqhkiG9w0BAQsFADB+MQswCQYDVQQGEwJV
// SIG // UzETMBEGA1UECBMKV2FzaGluZ3RvbjEQMA4GA1UEBxMH
// SIG // UmVkbW9uZDEeMBwGA1UEChMVTWljcm9zb2Z0IENvcnBv
// SIG // cmF0aW9uMSgwJgYDVQQDEx9NaWNyb3NvZnQgQ29kZSBT
// SIG // aWduaW5nIFBDQSAyMDExMB4XDTIwMTIxNTIxMzE0NVoX
// SIG // DTIxMTIwMjIxMzE0NVowdDELMAkGA1UEBhMCVVMxEzAR
// SIG // BgNVBAgTCldhc2hpbmd0b24xEDAOBgNVBAcTB1JlZG1v
// SIG // bmQxHjAcBgNVBAoTFU1pY3Jvc29mdCBDb3Jwb3JhdGlv
// SIG // bjEeMBwGA1UEAxMVTWljcm9zb2Z0IENvcnBvcmF0aW9u
// SIG // MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEA
// SIG // trsZWRAAo6nx5LhcqAsHy9uaHyPQ2VireMBI9yQUOPBj
// SIG // 7dVLA7/N+AnKFFDzJ7P+grT6GkOE4cv5GzjoP8yQJ6yX
// SIG // ojEKkXti7HW/zUiNoF11/ZWndf8j1Azl6OBjcD416tSW
// SIG // Yvh2VfdW1K+mY83j49YPm3qbKnfxwtV0nI9H092gMS0c
// SIG // pCUsxMRAZlPXksrjsFLqvgq4rnULVhjHSVOudL/yps3z
// SIG // OOmOpaPzAp56b898xC+zzHVHcKo/52IRht1FSC8V+7QH
// SIG // TG8+yzfuljiKU9QONa8GqDlZ7/vFGveB8IY2ZrtUu98n
// SIG // le0WWTcaIRHoCYvWGLLF2u1GVFJAggPipwIDAQABo4IB
// SIG // fjCCAXowHwYDVR0lBBgwFgYKKwYBBAGCN0wIAQYIKwYB
// SIG // BQUHAwMwHQYDVR0OBBYEFDj2zC/CHZDRrQnzJlT7byOl
// SIG // WfPjMFAGA1UdEQRJMEekRTBDMSkwJwYDVQQLEyBNaWNy
// SIG // b3NvZnQgT3BlcmF0aW9ucyBQdWVydG8gUmljbzEWMBQG
// SIG // A1UEBRMNMjMwMDEyKzQ2MzAwOTAfBgNVHSMEGDAWgBRI
// SIG // bmTlUAXTgqoXNzcitW2oynUClTBUBgNVHR8ETTBLMEmg
// SIG // R6BFhkNodHRwOi8vd3d3Lm1pY3Jvc29mdC5jb20vcGtp
// SIG // b3BzL2NybC9NaWNDb2RTaWdQQ0EyMDExXzIwMTEtMDct
// SIG // MDguY3JsMGEGCCsGAQUFBwEBBFUwUzBRBggrBgEFBQcw
// SIG // AoZFaHR0cDovL3d3dy5taWNyb3NvZnQuY29tL3BraW9w
// SIG // cy9jZXJ0cy9NaWNDb2RTaWdQQ0EyMDExXzIwMTEtMDct
// SIG // MDguY3J0MAwGA1UdEwEB/wQCMAAwDQYJKoZIhvcNAQEL
// SIG // BQADggIBAJ56h7Q8mFBWlQJLwCtHqqup4aC/eUmULt0Z
// SIG // 6We7XUPPUEd/vuwPuIa6+1eMcZpAeQTm0tGCvjACxNNm
// SIG // rY8FoD3aWEOvFnSxq6CWR5G2XYBERvu7RExZd2iheCqa
// SIG // EmhjrJGV6Uz5wmjKNj16ADFTBqbEBELMIpmatyEN50UH
// SIG // wZSdD6DDHDf/j5LPGUy9QaD2LCaaJLenKpefaugsqWWC
// SIG // MIMifPdh6bbcmxyoNWbUC1JUl3HETJboD4BHDWSWoDxI
// SIG // D2J4uG9dbJ40QIH9HckNMyPWi16k8VlFOaQiBYj09G9s
// SIG // LMc0agrchqqZBjPD/RmszvHmqJlSLQmAXCUgcgcf6UtH
// SIG // EmMAQRwGcSTg1KsUl6Ehg75k36lCV57Z1pC+KJKJNRYg
// SIG // g2eI6clzkLp2+noCF75IEO429rjtujsNJvEcJXg74TjK
// SIG // 5x7LqYjj26Myq6EmuqWhbVUofPWm1EqKEfEHWXInppqB
// SIG // YXFpBMBYOLKc72DT+JyLNfd9utVsk2kTGaHHhrp+xgk9
// SIG // kZeud7lI/hfoPeHOtwIc0quJIXS+B5RSD9nj79vbJn1J
// SIG // x7RqusmBQy509Kv2Pg4t48JaBfBFpJB0bUrl5RVG05sK
// SIG // /5Qw4G6WYioS0uwgUw499iNC+Yud9vrh3M8PNqGQ5mJm
// SIG // JiFEjG2ToEuuYe/e64+SSejpHhFCaAFcMIIHejCCBWKg
// SIG // AwIBAgIKYQ6Q0gAAAAAAAzANBgkqhkiG9w0BAQsFADCB
// SIG // iDELMAkGA1UEBhMCVVMxEzARBgNVBAgTCldhc2hpbmd0
// SIG // b24xEDAOBgNVBAcTB1JlZG1vbmQxHjAcBgNVBAoTFU1p
// SIG // Y3Jvc29mdCBDb3Jwb3JhdGlvbjEyMDAGA1UEAxMpTWlj
// SIG // cm9zb2Z0IFJvb3QgQ2VydGlmaWNhdGUgQXV0aG9yaXR5
// SIG // IDIwMTEwHhcNMTEwNzA4MjA1OTA5WhcNMjYwNzA4MjEw
// SIG // OTA5WjB+MQswCQYDVQQGEwJVUzETMBEGA1UECBMKV2Fz
// SIG // aGluZ3RvbjEQMA4GA1UEBxMHUmVkbW9uZDEeMBwGA1UE
// SIG // ChMVTWljcm9zb2Z0IENvcnBvcmF0aW9uMSgwJgYDVQQD
// SIG // Ex9NaWNyb3NvZnQgQ29kZSBTaWduaW5nIFBDQSAyMDEx
// SIG // MIICIjANBgkqhkiG9w0BAQEFAAOCAg8AMIICCgKCAgEA
// SIG // q/D6chAcLq3YbqqCEE00uvK2WCGfQhsqa+laUKq4Bjga
// SIG // BEm6f8MMHt03a8YS2AvwOMKZBrDIOdUBFDFC04kNeWSH
// SIG // fpRgJGyvnkmc6Whe0t+bU7IKLMOv2akrrnoJr9eWWcpg
// SIG // GgXpZnboMlImEi/nqwhQz7NEt13YxC4Ddato88tt8zpc
// SIG // oRb0RrrgOGSsbmQ1eKagYw8t00CT+OPeBw3VXHmlSSnn
// SIG // Db6gE3e+lD3v++MrWhAfTVYoonpy4BI6t0le2O3tQ5GD
// SIG // 2Xuye4Yb2T6xjF3oiU+EGvKhL1nkkDstrjNYxbc+/jLT
// SIG // swM9sbKvkjh+0p2ALPVOVpEhNSXDOW5kf1O6nA+tGSOE
// SIG // y/S6A4aN91/w0FK/jJSHvMAhdCVfGCi2zCcoOCWYOUo2
// SIG // z3yxkq4cI6epZuxhH2rhKEmdX4jiJV3TIUs+UsS1Vz8k
// SIG // A/DRelsv1SPjcF0PUUZ3s/gA4bysAoJf28AVs70b1FVL
// SIG // 5zmhD+kjSbwYuER8ReTBw3J64HLnJN+/RpnF78IcV9uD
// SIG // jexNSTCnq47f7Fufr/zdsGbiwZeBe+3W7UvnSSmnEyim
// SIG // p31ngOaKYnhfsi+E11ecXL93KCjx7W3DKI8sj0A3T8Hh
// SIG // hUSJxAlMxdSlQy90lfdu+HggWCwTXWCVmj5PM4TasIgX
// SIG // 3p5O9JawvEagbJjS4NaIjAsCAwEAAaOCAe0wggHpMBAG
// SIG // CSsGAQQBgjcVAQQDAgEAMB0GA1UdDgQWBBRIbmTlUAXT
// SIG // gqoXNzcitW2oynUClTAZBgkrBgEEAYI3FAIEDB4KAFMA
// SIG // dQBiAEMAQTALBgNVHQ8EBAMCAYYwDwYDVR0TAQH/BAUw
// SIG // AwEB/zAfBgNVHSMEGDAWgBRyLToCMZBDuRQFTuHqp8cx
// SIG // 0SOJNDBaBgNVHR8EUzBRME+gTaBLhklodHRwOi8vY3Js
// SIG // Lm1pY3Jvc29mdC5jb20vcGtpL2NybC9wcm9kdWN0cy9N
// SIG // aWNSb29DZXJBdXQyMDExXzIwMTFfMDNfMjIuY3JsMF4G
// SIG // CCsGAQUFBwEBBFIwUDBOBggrBgEFBQcwAoZCaHR0cDov
// SIG // L3d3dy5taWNyb3NvZnQuY29tL3BraS9jZXJ0cy9NaWNS
// SIG // b29DZXJBdXQyMDExXzIwMTFfMDNfMjIuY3J0MIGfBgNV
// SIG // HSAEgZcwgZQwgZEGCSsGAQQBgjcuAzCBgzA/BggrBgEF
// SIG // BQcCARYzaHR0cDovL3d3dy5taWNyb3NvZnQuY29tL3Br
// SIG // aW9wcy9kb2NzL3ByaW1hcnljcHMuaHRtMEAGCCsGAQUF
// SIG // BwICMDQeMiAdAEwAZQBnAGEAbABfAHAAbwBsAGkAYwB5
// SIG // AF8AcwB0AGEAdABlAG0AZQBuAHQALiAdMA0GCSqGSIb3
// SIG // DQEBCwUAA4ICAQBn8oalmOBUeRou09h0ZyKbC5YR4WOS
// SIG // mUKWfdJ5DJDBZV8uLD74w3LRbYP+vj/oCso7v0epo/Np
// SIG // 22O/IjWll11lhJB9i0ZQVdgMknzSGksc8zxCi1LQsP1r
// SIG // 4z4HLimb5j0bpdS1HXeUOeLpZMlEPXh6I/MTfaaQdION
// SIG // 9MsmAkYqwooQu6SpBQyb7Wj6aC6VoCo/KmtYSWMfCWlu
// SIG // WpiW5IP0wI/zRive/DvQvTXvbiWu5a8n7dDd8w6vmSiX
// SIG // mE0OPQvyCInWH8MyGOLwxS3OW560STkKxgrCxq2u5bLZ
// SIG // 2xWIUUVYODJxJxp/sfQn+N4sOiBpmLJZiWhub6e3dMNA
// SIG // BQamASooPoI/E01mC8CzTfXhj38cbxV9Rad25UAqZaPD
// SIG // XVJihsMdYzaXht/a8/jyFqGaJ+HNpZfQ7l1jQeNbB5yH
// SIG // PgZ3BtEGsXUfFL5hYbXw3MYbBL7fQccOKO7eZS/sl/ah
// SIG // XJbYANahRr1Z85elCUtIEJmAH9AAKcWxm6U/RXceNcbS
// SIG // oqKfenoi+kiVH6v7RyOA9Z74v2u3S5fi63V4GuzqN5l5
// SIG // GEv/1rMjaHXmr/r8i+sLgOppO6/8MO0ETI7f33VtY5E9
// SIG // 0Z1WTk+/gFcioXgRMiF670EKsT/7qMykXcGhiJtXcVZO
// SIG // SEXAQsmbdlsKgEhr/Xmfwb1tbWrJUnMTDXpQzTGCFa8w
// SIG // ghWrAgEBMIGVMH4xCzAJBgNVBAYTAlVTMRMwEQYDVQQI
// SIG // EwpXYXNoaW5ndG9uMRAwDgYDVQQHEwdSZWRtb25kMR4w
// SIG // HAYDVQQKExVNaWNyb3NvZnQgQ29ycG9yYXRpb24xKDAm
// SIG // BgNVBAMTH01pY3Jvc29mdCBDb2RlIFNpZ25pbmcgUENB
// SIG // IDIwMTECEzMAAAHfa/AukqdKtNAAAAAAAd8wDQYJYIZI
// SIG // AWUDBAIBBQCgggEBMBkGCSqGSIb3DQEJAzEMBgorBgEE
// SIG // AYI3AgEEMBwGCisGAQQBgjcCAQsxDjAMBgorBgEEAYI3
// SIG // AgEVMC8GCSqGSIb3DQEJBDEiBCA1y2df99E9DpNjbjFm
// SIG // 89HV5omCqUenc9vZjs4cbFfXzjCBlAYKKwYBBAGCNwIB
// SIG // DDGBhTCBgqBkgGIATQBpAGMAcgBvAHMAbwBmAHQALgBE
// SIG // AHkAbgBhAG0AaQBjAHMALgBGAHIAYQBtAGUAdwBvAHIA
// SIG // awAuAFUASQAuAFcAaQBuAEYAbwByAG0AcwAuAEMAbwBu
// SIG // AHQAcgBvAGwAc6EagBhodHRwOi8vd3d3Lm1pY3Jvc29m
// SIG // dC5jb20wDQYJKoZIhvcNAQEBBQAEggEATn3mpokRmWUk
// SIG // YyuuLMuWD2Uc4Cy/NHcp7jdEY+moIEmq0lOQ/W6QzEhx
// SIG // aIf9Eu/v2xjNgu5ymKTLeKxIB6ITtUYctvwy14w721i2
// SIG // Ssqld52hEm9SOBrFmhzA/TVWzxBPB/xzJpJTkadrVHYH
// SIG // fbvarxqu7pz1LnSyQsNfyG+NbrpCHXjcW6mmp8eI/+aX
// SIG // xy46P6yjG+4rMVGJyS27nZYE4nYwcdQKhhFD/MDNbVql
// SIG // mnRTCjtxd20GdQLOPOYWJtunIQlD65YBjBax/IbohVHC
// SIG // KFp9F73khlct4lF9UhKkmqdfYqVRtpQoWwwK3lQfxDta
// SIG // lYcngJR4q3w/+IAPulB94aGCEuUwghLhBgorBgEEAYI3
// SIG // AwMBMYIS0TCCEs0GCSqGSIb3DQEHAqCCEr4wghK6AgED
// SIG // MQ8wDQYJYIZIAWUDBAIBBQAwggFRBgsqhkiG9w0BCRAB
// SIG // BKCCAUAEggE8MIIBOAIBAQYKKwYBBAGEWQoDATAxMA0G
// SIG // CWCGSAFlAwQCAQUABCCBTTKBMw5Tu1dkuwGQB5y88cAF
// SIG // 7yU6jYyU8ex4MQIvdQIGYUS6XUecGBMyMDIxMDkyOTEy
// SIG // MDkzMC4zMDZaMASAAgH0oIHQpIHNMIHKMQswCQYDVQQG
// SIG // EwJVUzETMBEGA1UECBMKV2FzaGluZ3RvbjEQMA4GA1UE
// SIG // BxMHUmVkbW9uZDEeMBwGA1UEChMVTWljcm9zb2Z0IENv
// SIG // cnBvcmF0aW9uMSUwIwYDVQQLExxNaWNyb3NvZnQgQW1l
// SIG // cmljYSBPcGVyYXRpb25zMSYwJAYDVQQLEx1UaGFsZXMg
// SIG // VFNTIEVTTjpBRTJDLUUzMkItMUFGQzElMCMGA1UEAxMc
// SIG // TWljcm9zb2Z0IFRpbWUtU3RhbXAgU2VydmljZaCCDjww
// SIG // ggTxMIID2aADAgECAhMzAAABSKKIRVa8L4C/AAAAAAFI
// SIG // MA0GCSqGSIb3DQEBCwUAMHwxCzAJBgNVBAYTAlVTMRMw
// SIG // EQYDVQQIEwpXYXNoaW5ndG9uMRAwDgYDVQQHEwdSZWRt
// SIG // b25kMR4wHAYDVQQKExVNaWNyb3NvZnQgQ29ycG9yYXRp
// SIG // b24xJjAkBgNVBAMTHU1pY3Jvc29mdCBUaW1lLVN0YW1w
// SIG // IFBDQSAyMDEwMB4XDTIwMTExMjE4MjU1NloXDTIyMDIx
// SIG // MTE4MjU1NlowgcoxCzAJBgNVBAYTAlVTMRMwEQYDVQQI
// SIG // EwpXYXNoaW5ndG9uMRAwDgYDVQQHEwdSZWRtb25kMR4w
// SIG // HAYDVQQKExVNaWNyb3NvZnQgQ29ycG9yYXRpb24xJTAj
// SIG // BgNVBAsTHE1pY3Jvc29mdCBBbWVyaWNhIE9wZXJhdGlv
// SIG // bnMxJjAkBgNVBAsTHVRoYWxlcyBUU1MgRVNOOkFFMkMt
// SIG // RTMyQi0xQUZDMSUwIwYDVQQDExxNaWNyb3NvZnQgVGlt
// SIG // ZS1TdGFtcCBTZXJ2aWNlMIIBIjANBgkqhkiG9w0BAQEF
// SIG // AAOCAQ8AMIIBCgKCAQEA9/94rxWEitHRrXF2mfKTSxAE
// SIG // W62iXsK8ovyYG2ipau4YRSFNRJGNBzIhUZtv1rLpLetp
// SIG // Nuc7w8Vten6YYOfO+vpdcGJwpYHv6xZa0dlLtVsLRZnN
// SIG // cRqcuPrsaGwhDHiBQxoS+QzU22zorC6wVGG8l6+3z88W
// SIG // 1ZBMCQz+RRtp9K6Najo3oCJCyI11OqmoXbkMU37DzhKf
// SIG // I4KjCp/vn6R+n71ypXsFs3bH74YmeB+CKtQkzp/n5Man
// SIG // A8Ex2JGGWIKpvtV9ce+OfK6evaoxXlT9xmwLyW2N2xZa
// SIG // ubssa4j3GcQ2awen9cAC16ztvyHX1RHcE1qiSA2QSY08
// SIG // nEIYcUt4tQIDAQABo4IBGzCCARcwHQYDVR0OBBYEFIcy
// SIG // 8GmfDgS0SR9LPROt6SHFiaJHMB8GA1UdIwQYMBaAFNVj
// SIG // OlyKMZDzQ3t8RhvFM2hahW1VMFYGA1UdHwRPME0wS6BJ
// SIG // oEeGRWh0dHA6Ly9jcmwubWljcm9zb2Z0LmNvbS9wa2kv
// SIG // Y3JsL3Byb2R1Y3RzL01pY1RpbVN0YVBDQV8yMDEwLTA3
// SIG // LTAxLmNybDBaBggrBgEFBQcBAQROMEwwSgYIKwYBBQUH
// SIG // MAKGPmh0dHA6Ly93d3cubWljcm9zb2Z0LmNvbS9wa2kv
// SIG // Y2VydHMvTWljVGltU3RhUENBXzIwMTAtMDctMDEuY3J0
// SIG // MAwGA1UdEwEB/wQCMAAwEwYDVR0lBAwwCgYIKwYBBQUH
// SIG // AwgwDQYJKoZIhvcNAQELBQADggEBAGYSlsGzJwvUMsHK
// SIG // 5YLNKl/W4cYmRr3vvCRA9u4ToshmvEfZ6sx4OPqujSn2
// SIG // F30utrjFCadrvie7SDVE3/9boC/iuEcLD1XoQ2rEiSY/
// SIG // u26CMWT/AFP8UHVWO6oJkBpneBfnOYZCSbZejUXmBPdP
// SIG // EOvfKo9Zg6a9DMfuC4T/7U6i+h6WRFEZYRTnXZ8i0rVQ
// SIG // hXXzSNchhz/Z9MjdSn4RhFd7OzAc6RSV8Dn5cIMhPXME
// SIG // PI4zk1aTUXQqi/z+VYggKNnXIh43dbtYtUOEGesW9Pgd
// SIG // R3WRURCzohcH9LId2dcTnkhXB4NKyxPq7Hh8+EIb6BI+
// SIG // 4fWw/FTe/x5wg8FqQSUwggZxMIIEWaADAgECAgphCYEq
// SIG // AAAAAAACMA0GCSqGSIb3DQEBCwUAMIGIMQswCQYDVQQG
// SIG // EwJVUzETMBEGA1UECBMKV2FzaGluZ3RvbjEQMA4GA1UE
// SIG // BxMHUmVkbW9uZDEeMBwGA1UEChMVTWljcm9zb2Z0IENv
// SIG // cnBvcmF0aW9uMTIwMAYDVQQDEylNaWNyb3NvZnQgUm9v
// SIG // dCBDZXJ0aWZpY2F0ZSBBdXRob3JpdHkgMjAxMDAeFw0x
// SIG // MDA3MDEyMTM2NTVaFw0yNTA3MDEyMTQ2NTVaMHwxCzAJ
// SIG // BgNVBAYTAlVTMRMwEQYDVQQIEwpXYXNoaW5ndG9uMRAw
// SIG // DgYDVQQHEwdSZWRtb25kMR4wHAYDVQQKExVNaWNyb3Nv
// SIG // ZnQgQ29ycG9yYXRpb24xJjAkBgNVBAMTHU1pY3Jvc29m
// SIG // dCBUaW1lLVN0YW1wIFBDQSAyMDEwMIIBIjANBgkqhkiG
// SIG // 9w0BAQEFAAOCAQ8AMIIBCgKCAQEAqR0NvHcRijog7PwT
// SIG // l/X6f2mUa3RUENWlCgCChfvtfGhLLF/Fw+Vhwna3PmYr
// SIG // W/AVUycEMR9BGxqVHc4JE458YTBZsTBED/FgiIRUQwzX
// SIG // Tbg4CLNC3ZOs1nMwVyaCo0UN0Or1R4HNvyRgMlhgRvJY
// SIG // R4YyhB50YWeRX4FUsc+TTJLBxKZd0WETbijGGvmGgLvf
// SIG // YfxGwScdJGcSchohiq9LZIlQYrFd/XcfPfBXday9ikJN
// SIG // QFHRD5wGPmd/9WbAA5ZEfu/QS/1u5ZrKsajyeioKMfDa
// SIG // TgaRtogINeh4HLDpmc085y9Euqf03GS9pAHBIAmTeM38
// SIG // vMDJRF1eFpwBBU8iTQIDAQABo4IB5jCCAeIwEAYJKwYB
// SIG // BAGCNxUBBAMCAQAwHQYDVR0OBBYEFNVjOlyKMZDzQ3t8
// SIG // RhvFM2hahW1VMBkGCSsGAQQBgjcUAgQMHgoAUwB1AGIA
// SIG // QwBBMAsGA1UdDwQEAwIBhjAPBgNVHRMBAf8EBTADAQH/
// SIG // MB8GA1UdIwQYMBaAFNX2VsuP6KJcYmjRPZSQW9fOmhjE
// SIG // MFYGA1UdHwRPME0wS6BJoEeGRWh0dHA6Ly9jcmwubWlj
// SIG // cm9zb2Z0LmNvbS9wa2kvY3JsL3Byb2R1Y3RzL01pY1Jv
// SIG // b0NlckF1dF8yMDEwLTA2LTIzLmNybDBaBggrBgEFBQcB
// SIG // AQROMEwwSgYIKwYBBQUHMAKGPmh0dHA6Ly93d3cubWlj
// SIG // cm9zb2Z0LmNvbS9wa2kvY2VydHMvTWljUm9vQ2VyQXV0
// SIG // XzIwMTAtMDYtMjMuY3J0MIGgBgNVHSABAf8EgZUwgZIw
// SIG // gY8GCSsGAQQBgjcuAzCBgTA9BggrBgEFBQcCARYxaHR0
// SIG // cDovL3d3dy5taWNyb3NvZnQuY29tL1BLSS9kb2NzL0NQ
// SIG // Uy9kZWZhdWx0Lmh0bTBABggrBgEFBQcCAjA0HjIgHQBM
// SIG // AGUAZwBhAGwAXwBQAG8AbABpAGMAeQBfAFMAdABhAHQA
// SIG // ZQBtAGUAbgB0AC4gHTANBgkqhkiG9w0BAQsFAAOCAgEA
// SIG // B+aIUQ3ixuCYP4FxAz2do6Ehb7Prpsz1Mb7PBeKp/vpX
// SIG // bRkws8LFZslq3/Xn8Hi9x6ieJeP5vO1rVFcIK1GCRBL7
// SIG // uVOMzPRgEop2zEBAQZvcXBf/XPleFzWYJFZLdO9CEMiv
// SIG // v3/Gf/I3fVo/HPKZeUqRUgCvOA8X9S95gWXZqbVr5MfO
// SIG // 9sp6AG9LMEQkIjzP7QOllo9ZKby2/QThcJ8ySif9Va8v
// SIG // /rbljjO7Yl+a21dA6fHOmWaQjP9qYn/dxUoLkSbiOewZ
// SIG // SnFjnXshbcOco6I8+n99lmqQeKZt0uGc+R38ONiU9Mal
// SIG // CpaGpL2eGq4EQoO4tYCbIjggtSXlZOz39L9+Y1klD3ou
// SIG // OVd2onGqBooPiRa6YacRy5rYDkeagMXQzafQ732D8OE7
// SIG // cQnfXXSYIghh2rBQHm+98eEA3+cxB6STOvdlR3jo+KhI
// SIG // q/fecn5ha293qYHLpwmsObvsxsvYgrRyzR30uIUBHoD7
// SIG // G4kqVDmyW9rIDVWZeodzOwjmmC3qjeAzLhIp9cAvVCch
// SIG // 98isTtoouLGp25ayp0Kiyc8ZQU3ghvkqmqMRZjDTu3Qy
// SIG // S99je/WZii8bxyGvWbWu3EQ8l1Bx16HSxVXjad5XwdHe
// SIG // MMD9zOZN+w2/XU/pnR4ZOC+8z1gFLu8NoFA12u8JJxzV
// SIG // s341Hgi62jbb01+P3nSISRKhggLOMIICNwIBATCB+KGB
// SIG // 0KSBzTCByjELMAkGA1UEBhMCVVMxEzARBgNVBAgTCldh
// SIG // c2hpbmd0b24xEDAOBgNVBAcTB1JlZG1vbmQxHjAcBgNV
// SIG // BAoTFU1pY3Jvc29mdCBDb3Jwb3JhdGlvbjElMCMGA1UE
// SIG // CxMcTWljcm9zb2Z0IEFtZXJpY2EgT3BlcmF0aW9uczEm
// SIG // MCQGA1UECxMdVGhhbGVzIFRTUyBFU046QUUyQy1FMzJC
// SIG // LTFBRkMxJTAjBgNVBAMTHE1pY3Jvc29mdCBUaW1lLVN0
// SIG // YW1wIFNlcnZpY2WiIwoBATAHBgUrDgMCGgMVAIcrgpa6
// SIG // HFn+EiHEWnwBF9UYbOs5oIGDMIGApH4wfDELMAkGA1UE
// SIG // BhMCVVMxEzARBgNVBAgTCldhc2hpbmd0b24xEDAOBgNV
// SIG // BAcTB1JlZG1vbmQxHjAcBgNVBAoTFU1pY3Jvc29mdCBD
// SIG // b3Jwb3JhdGlvbjEmMCQGA1UEAxMdTWljcm9zb2Z0IFRp
// SIG // bWUtU3RhbXAgUENBIDIwMTAwDQYJKoZIhvcNAQEFBQAC
// SIG // BQDk/mHMMCIYDzIwMjEwOTI5MTE1MzQ4WhgPMjAyMTA5
// SIG // MzAxMTUzNDhaMHcwPQYKKwYBBAGEWQoEATEvMC0wCgIF
// SIG // AOT+YcwCAQAwCgIBAAICCaICAf8wBwIBAAICEVowCgIF
// SIG // AOT/s0wCAQAwNgYKKwYBBAGEWQoEAjEoMCYwDAYKKwYB
// SIG // BAGEWQoDAqAKMAgCAQACAwehIKEKMAgCAQACAwGGoDAN
// SIG // BgkqhkiG9w0BAQUFAAOBgQBoP+knjZvdUXgogHHb3WTT
// SIG // TWi20GaFpap/PLzCCeeEq4bZCOvA9aXTYz4USpKAxLNj
// SIG // URJOeeF4HWibMFAbYwsOa7g5EFJpHaOYtot5ozBBxsr4
// SIG // D1zRIBHrHHiG+N43HiP6pHg5CgT11IJrzcXq4eE1NKri
// SIG // Gq0+aoQwpDsGRErhzTGCAw0wggMJAgEBMIGTMHwxCzAJ
// SIG // BgNVBAYTAlVTMRMwEQYDVQQIEwpXYXNoaW5ndG9uMRAw
// SIG // DgYDVQQHEwdSZWRtb25kMR4wHAYDVQQKExVNaWNyb3Nv
// SIG // ZnQgQ29ycG9yYXRpb24xJjAkBgNVBAMTHU1pY3Jvc29m
// SIG // dCBUaW1lLVN0YW1wIFBDQSAyMDEwAhMzAAABSKKIRVa8
// SIG // L4C/AAAAAAFIMA0GCWCGSAFlAwQCAQUAoIIBSjAaBgkq
// SIG // hkiG9w0BCQMxDQYLKoZIhvcNAQkQAQQwLwYJKoZIhvcN
// SIG // AQkEMSIEID/rRT9kwxHObmESIdDYXLpiFrjz5Tl0y2lJ
// SIG // XOekJWcJMIH6BgsqhkiG9w0BCRACLzGB6jCB5zCB5DCB
// SIG // vQQgqZAa6ox5ob8mH+bU3E7w+WOGvle/U8FVek9WgMHb
// SIG // aNgwgZgwgYCkfjB8MQswCQYDVQQGEwJVUzETMBEGA1UE
// SIG // CBMKV2FzaGluZ3RvbjEQMA4GA1UEBxMHUmVkbW9uZDEe
// SIG // MBwGA1UEChMVTWljcm9zb2Z0IENvcnBvcmF0aW9uMSYw
// SIG // JAYDVQQDEx1NaWNyb3NvZnQgVGltZS1TdGFtcCBQQ0Eg
// SIG // MjAxMAITMwAAAUiiiEVWvC+AvwAAAAABSDAiBCCLPgJO
// SIG // hyEQ41BkscVisuN6qc9bKENyr05beAWEfOKvQzANBgkq
// SIG // hkiG9w0BAQsFAASCAQAI72geE7nVKtyzkrnD7DfsSL2p
// SIG // owQFviPRZCZarklh9WE1agxdZnWuUskoX63wkNJivukz
// SIG // 8IbOEErTU6ih7hd8G7XnBTXx0b/GqiV3rwrNnwGVpZZu
// SIG // 0Bm3sOUz/B3UQX+Tt7+zqdnFuzInyLsYgdjMJp8EOAA7
// SIG // 1ZgnBBkizX+bZ5hJ5pMttD93wtBU5qrUb4B6xV7z0wj6
// SIG // vd8cZDqS96nuyUrNiOtfeBZfB7UjQnU4FTV5bQf9hbja
// SIG // 8gaRviOYKrj3mfFOsFPA4hI0BS0O0sOJ1fjZSQBbH+dz
// SIG // o/zrpjEiKCTgXMmmYw3YEByCszg3lpNFv+WQUzEAQWpi
// SIG // D6U051i1
// SIG // End signature block
